# Task
Perform stratified sampling on the data from "https://raw.githubusercontent.com/plotly/datasets/master/Earthquakes.csv" by generating geohashes from the 'long' and 'lat' columns, then save the sampled data to a downloadable CSV file excluding the geohash column.

## Read CSV

### Subtask:
Read the CSV file from the provided URL into a pandas DataFrame.

**Reasoning**:
To read the CSV file from the given URL into a pandas DataFrame and display its first few rows, I will import pandas, define the URL, use `pd.read_csv()` to load the data, and then use `df.head()`.

In [23]:
import pandas as pd

# Define the URL for the CSV file
url = "https://raw.githubusercontent.com/IsamAljawarneh/datasets/refs/heads/master/data/Chicago/AQ_data/chicago_eclipse_data_part_1.csv"

# Read the CSV file into a DataFrame
df = pd.read_csv(url)

# Display the first few rows of the DataFrame to verify
print("DataFrame loaded successfully. First 5 rows:")
df.head()

DataFrame loaded successfully. First 5 rows:

,City,DeviceId,LocationName,Latitude,Longitude,ReadingDateTimeUTC,PM25,CalibratedPM25,CalibratedO3,CalibratedNO2,CO,Temperature,Humidity,BatteryLevel,PercentBattery,CellSignal
0,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:03:00,5.561094,NaN,NaN,NaN,0.123580,27.383499,55.128479,4.237187,93.964844,-76.0
1,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:08:10,6.633914,NaN,NaN,NaN,0.132103,27.079086,55.059814,4.236094,93.964844,-81.0
2,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:13:20,4.068707,NaN,NaN,NaN,0.131126,27.079086,55.035400,4.236406,93.964844,-80.0
3,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:18:30,6.351702,NaN,NaN,NaN,0.138784,26.945572,54.632568,4.236094,93.863281,-82.0
4,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:23:40,9.574065,NaN,NaN,NaN,0.413070,26.828079,53.907776,4.235938,93.863281,-81.0

**Reasoning**:
The previous attempt to read the CSV failed because the URL was incorrect (HTTP Error 404). I will update the URL to the correct one for the `earthquake.csv` file on Plotly's GitHub repository and re-execute the code.

## Geohash Coordinates

### Subtask:
Generate geohashes for the 'long' and 'lat' columns of the DataFrame.

**Reasoning**:
The subtask requires generating geohashes, which necessitates the `python-geohash` library. I will first install this library to ensure it's available for use.

In [24]:
!pip install python-geohash
print("python-geohash library installed.")

Requirement already satisfied: python-geohash in /usr/local/lib/python3.12/dist-packages (0.8.5)
python-geohash library installed.

**Reasoning**:
The previous `pip install` command failed due to a `SyntaxError` because it was not executed as a shell command. I will correct this by adding an exclamation mark (!) before `pip install` to ensure it runs correctly in the notebook environment. After installing the library, I will import it and then generate geohashes from the 'lat' and 'long' columns, adding them to a new 'geohash' column in the DataFrame `df` with a precision of 7.

In [25]:
!pip install python-geohash
import geohash

print("python-geohash library installed and imported.")

# Generate geohashes
df['geohash'] = df.apply(lambda row: geohash.encode(row['Latitude'], row['Longitude'], precision=7), axis=1)

# Display the first few rows of the DataFrame to verify
print("DataFrame with 'geohash' column:")
display(df.head())

Requirement already satisfied: python-geohash in /usr/local/lib/python3.12/dist-packages (0.8.5)
python-geohash library installed and imported.
DataFrame with 'geohash' column:

,City,DeviceId,LocationName,Latitude,Longitude,ReadingDateTimeUTC,PM25,CalibratedPM25,CalibratedO3,CalibratedNO2,CO,Temperature,Humidity,BatteryLevel,PercentBattery,CellSignal,geohash
0,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:03:00,5.561094,NaN,NaN,NaN,0.123580,27.383499,55.128479,4.237187,93.964844,-76.0,dp3ty08
1,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:08:10,6.633914,NaN,NaN,NaN,0.132103,27.079086,55.059814,4.236094,93.964844,-81.0,dp3ty08
2,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:13:20,4.068707,NaN,NaN,NaN,0.131126,27.079086,55.035400,4.236406,93.964844,-80.0,dp3ty08
3,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:18:30,6.351702,NaN,NaN,NaN,0.138784,26.945572,54.632568,4.236094,93.863281,-82.0,dp3ty08
4,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:23:40,9.574065,NaN,NaN,NaN,0.413070,26.828079,53.907776,4.235938,93.863281,-81.0,dp3ty08

## Stratified Sampling and Downloadable CSV

This section summarizes the final steps of the task:

1.  **Stratified Sampling**: The DataFrame `df` (which includes the generated 'geohash' column from 'Latitude' and 'Longitude') was used to perform stratified sampling. A `sampling_fraction` of 0.1 was applied, ensuring at least one sample from each geohash group to maintain geographical representation. The result is stored in `df_sampled`.
2.  **Excluding Geohash Column**: The 'geohash' column, used for stratification, was dropped from `df_sampled` to create `df_to_save` before saving, as per the task's requirement.
3.  **Saving to CSV**: The `df_to_save` DataFrame was saved to a CSV file named `'stratified_sampled_data.csv'`.
4.  **Downloadable Output**: The generated CSV file was made available for download, providing the final sampled dataset.

In [26]:
import pandas as pd
from google.colab import files

# Ensure df is defined from previous steps (assuming it is from earlier successful execution)
# Ensure 'geohash' column is defined in df (assuming it is from earlier successful execution)

sampling_fraction = 0.8

def stratified_sampler(group, fraction):
    """Samples a fraction of a group, ensuring at least one sample if the group is not empty."""
    n_samples = max(1, int(len(group) * fraction)) if len(group) > 0 else 0
    return group.sample(n=n_samples, random_state=42)

# Perform stratified sampling to define df_sampled
df_sampled = df.groupby('geohash', group_keys=False).apply(stratified_sampler, fraction=sampling_fraction)

# Drop the 'geohash' column before saving
df_to_save = df_sampled.drop(columns=['geohash'])

# Define the filename for the output CSV
output_filename = 'stratified_sampled_data.csv'

# Save the DataFrame to a CSV file
df_to_save.to_csv(output_filename, index=False)

print(f"Sampled data saved to '{output_filename}'.")

# Make the file downloadable
files.download(output_filename)
print("Your file is ready for download!")

/tmp/ipython-input-1554659933.py:15: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_sampled = df.groupby('geohash', group_keys=False).apply(stratified_sampler, fraction=sampling_fraction)

Sampled data saved to 'stratified_sampled_data.csv'.

Your file is ready for download!